cc_binary(
    name = "signaling",
    includes = ["include"],  # Include path for headers
    srcs = ["signaling.cc"],
    copts = ["-std=c++20"],
)

cc_binary(
    name = "rendezvous",
    includes = ["include"],  # Include path for headers
    srcs = ["rendezvous.cc"],
    copts = ["-std=c++20"],
)

cc_binary(
    name = "mutex",
    includes = ["include"],  # Include path for headers
    srcs = ["mutex.cc"],
    copts = ["-std=c++20"],
)

cc_binary(
    name = "multiplex",
    includes = ["include"],  # Include path for headers
    srcs = ["multiplex.cc"],
    copts = ["-std=c++20"],
)

cc_binary(
    name = "barrier",
    includes = ["include"],  # Include path for headers
    srcs = ["barrier.cc"],
    copts = ["-std=c++20"],
)

cc_binary(
    name = "reusable_barrier",
    includes = ["include"],  # Include path for headers
    srcs = ["reusable_barrier.cc"],
    copts = ["-std=c++20"],
)

cc_binary(
    name = "queue",
    includes = ["include"],  # Include path for headers
    srcs = ["queue.cc"],
    copts = ["-std=c++20"],
)
