
cc_binary(
    name = "circular",
    includes = ["include"],  # Include path for headers
    srcs = ["circular.cc"],
    copts = ["-std=c++20"],
)

cc_binary(
    name = "circular2",
    includes = ["include"],  # Include path for headers
    srcs = ["circular2.cc"],
    copts = ["-std=c++20"],
)

cc_binary(
    name = "circular3",
    includes = ["include"],  # Include path for headers
    srcs = ["circular3.cc"],
    copts = ["-std=c++20"],
)