cc_test(
    name = "circular-queue",
    srcs = ["circular-queue-test.cc"],
    deps = [
        "//src/circular-queue:circular-queue-lib",
        "@googletest//:gtest_main",  # Updated dependency reference
    ],
    includes = ["include"],  # Include path for headers
    copts = ["-std=c++20", "-Iinclude/circular-queue"],
)

cc_test(
    name = "circular-queue2",
    srcs = ["circular-queue2-test.cc"],
    deps = [
        "//src/circular-queue:circular-queue2-lib",
        "@googletest//:gtest_main",  # Updated dependency reference
    ],
    includes = ["include"],  # Include path for headers
    copts = ["-std=c++20", "-Iinclude/circular-queue"],
)

cc_test(
    name = "circular-queue3",
    srcs = ["circular-queue3-test.cc"],
    deps = [
        "//src/circular-queue:circular-queue3-lib",
        "@googletest//:gtest_main",  # Updated dependency reference
    ],
    includes = ["include"],  # Include path for headers
    copts = ["-std=c++20", "-Iinclude/circular-queue"],
)